name: Deploy Logging Stack to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          cd ~
          if [ ! -d "SEP4_Logging" ]; then
            git clone https://github.com/NotNebu/SEP4_Logging.git
          fi
          cd SEP4_Logging
          git pull origin main
          docker-compose down || true
          docker-compose up -d --build
        EOF
